name: 🔨 Build Test

on:
  pull_request:
    paths:
      - '**.go'
      - '**.mod'
  workflow_dispatch:

jobs:
  lint:
    name: Lint Test
    if: ${{ !endsWith(github.actor, '[bot]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: projectdiscovery/actions/setup/go@v1
      - uses: projectdiscovery/actions/golangci-lint/v2@v1

  build:
    name: Test Builds
    needs: [lint]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: projectdiscovery/actions/setup/go@v1

      - name: Build
        run: go build .
        working-directory: cmd/dnsx/

      - name: Test
        run: go test ./...
        env:
          GH_ACTION: true
          PDCP_API_KEY: "${{ secrets.PDCP_API_KEY }}"

      - name: Integration Tests
        env:
          GH_ACTION: true
          PDCP_API_KEY: "${{ secrets.PDCP_API_KEY }}"
        run: bash run.sh
        working-directory: integration_tests/

      - name: Race Condition Tests
        run: go build -race .
        working-directory: cmd/dnsx/
